"""NutrientIngredientLink foreign keys fix

Revision ID: 6b4813665f52
Revises: d443e577aa58
Create Date: 2025-05-12 19:13:29.661995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6b4813665f52'
down_revision: Union[str, None] = 'd443e577aa58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'nutrientingredientlink', 'nutrient', ['nutrient_id'], ['id'])
    op.create_foreign_key(None, 'nutrientingredientlink', 'ingredient', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nutrientingredientlink', type_='foreignkey')
    op.drop_constraint(None, 'nutrientingredientlink', type_='foreignkey')
    # ### end Alembic commands ###
