# Generated by Django 5.0.6 on 2024-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_rename_ingridient_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.JSONField(blank=True, choices=[('Ов', 'Овощь'), ('Фр', 'Фрукт'), ('Зр', 'Зерно'), ('Мл', 'Молочный продукт'), ('Сп', 'Специя'), ('Др', 'Другое')], default='Ов'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='minerals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteins',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitamins',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
