# Generated by Django 5.0.6 on 2024-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='minerals',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='vitamins',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
