# Generated by Django 5.0.6 on 2024-07-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_alter_ingredient_minerals_alter_ingredient_vitamins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
