# Generated by Django 5.0.6 on 2024-07-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0012_alter_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
